### ISSUE TITLE
Support for PSR-11 container interop

### ISSUE THREAD

**Issue by fmasa** [nette/di#155]
- bug report? no
- feature request? yes

### Description
There is [PSR-11](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md) for DI containers that aims to bring interoperability between different DI containers. PSR itself is simple and support in Nette DI would make interop with components from different frameworks easier and wouldn't bring any BC breaks.

There are already several frameworks with PSR-11 support - ZF, Symfony, ...

I can prepare PR if needed.

**Comment by mabar** [comment]
PSR is not good idea. It not makes these frameworks 100% compatible, they always have their specials. But it is not biggest problem. Bigest problem is that they are not perfect.
Eg. proposals for cache. First had really bad naming convention, second had still problem with accessing cache two times, because they allowed to store null. It took them 2 years to have approach which Nette have as long as I know.
And huggable interface? Way to standardise circular references which are almost always bullshit and causes big problems in PHP.
I don't think they are bad at all, but it is step back for Nette.

**Comment by fmasa** [comment]
@mabar You mentioned several PSRs that have nothing to do with proposed one. I don't understand that whole anti-PSR attitude in Nette community (not all ppl ofc).

Please, read PSR-11 (link above) and you'll see, that goal is only to standardize API used to obtain services from DI as it doesn't care about internal mechanisms of implementor.

**Comment by JanTvrdik** [comment]
@fmasa What real-world problem of yours (if any) does PSR-11 support in Nette DI solve?

**Comment by mabar** [comment]
Yes, I did. I did it to show authors of PSRs are not enought skilled to say what should frameworks do.

And if you want to speak about PSR-11. DI is much more complex thing than container. If you want fast DI so compiler is minimal requirement. And it is part of API. Moreover [DI Container](https://api.nette.org/2.4/Nette.DI.Container.html) in Nette contains much more methods than just get and has. I am using them every day.
But ok, if you think it is enought so how you will use PRS-11 friendly interface? What is their $id. Is it name of class I need? It cannot be. It would be impossible to have two instances of same class. And document is saying that get method can return anything. Why not just object or null? Who would like to use DI for eg. strings?

**Comment by dg** [comment]
It can be really simply solved by CompilerExtension, that appends methods get(), set() and implements PSR's interface. 

If you think this is really useful, please make the extension. I do not think so, currently, but if it turns out to be really useful, I can include it directly into the distribution.

**Comment by dg** [comment]
I have an idea for a much more useful implementation which solves interoperability between different DI containers. Ability to implement interfaces like this 

```php
interface AppContainer
{
    function getApplication(): Nette\Application\Application;
}
```

It will create `getApplication()` instead of `get()`, and it will be strictly typed. In next step, `Configurator::createContainer()` can return `AppContainer` instead `Nette\DI\Container` and in `index.php` can be `$container->getApplication()->run()`.

**Comment by enumag** [comment]
@fmasa If you just need PSR-11 around Nette DIC you can use [Arachne/ContainerAdapter](https://github.com/Arachne/ContainerAdapter).

**Comment by fmasa** [comment]
@JanTvrdik I was currently experimenting with composing multiple containers. Nothing serious really. Just wanted to bring up the idea of PSR-11 in Nette DI.

@mabar PSR-11 aims to standardise only ServiceLocator-ish API, for the very reasons you mentioned.
> Yes, I did. I did it to show authors of PSRs are not enought skilled to say **what should frameworks do.**

That's not really the goal, **R** in PSR still stands for *Recommendation*.

@enumag Experimenting with [Arachne/ContainerAdapter](https://github.com/Arachne/ContainerAdapter) right now :slightly_smiling_face:

**Comment by fmasa** [comment]
Closing as [Arachne/ContainerAdapter](https://github.com/Arachne/ContainerAdapter) can be used and there is no need to add this to nette/di itself

**Comment by miloshavlicek** [comment]
@dg I think that it's time to officially apply PSR-11 for Nette framework.

**Comment by dg** [comment]
@miloshavlicek noproblem. But I need to know what it's good for.

**Comment by miloshavlicek** [comment]
@dg It's a standard. This discussion is like why use SI metrics or not.

**Comment by dg** [comment]
I develop the software to be useful to users, not for political reasons.

**Comment by miloshavlicek** [comment]
@dg Ok, let's Nette live in its own small world. :-)

Seriously, I would welcome the real reasons for your overall contempt for [PHP-FIG](https://www.php-fig.org/) standards. Isn't its mission for framework interoperability great? Little mindset changes like this can have a big positive impact. Or is there some jealousy in that? Let's put emotions aside. I've been watching you for a long time and I see that you are conservative in such matters, I think it's really a shame.

AFAIK PHP-FIG is based on a broad consensus without any real political reasons. Please, correct me, if I'm wrong. It's much more about mutual understanding and cooperation. 

My opinion is, simply said, Nette should respect standards, otherwise, it will die calmly and slowly.

**Comment by dg** [comment]
Nette absolutely respects all standards. If you say something else, you're lying.
