### ISSUE TITLE
Container::$parameters contains unresolved Statement instances

### ISSUE THREAD

**Issue by xificurk** [nette/di#221]
Version: dev-master, 3.0.x, 2.4.x

### Bug Description
Parameters attribute in generated DI container contain unresolved `Nette\DI\Definitions\Statement` instances.

### Steps To Reproduce
Generate container with the following config:
```
parameters:
	bar: ::getenv(FOO)
```
The generated code of DI container will have something like this in constructor:
```php
$this->parameters += [
	'bar' => Nette\PhpGenerator\Helpers::createObject('Nette\DI\Definitions\Statement', [
		'arguments' => ['FOO'],
		"\x00Nette\\DI\\Definitions\\Statement\x00entity" => ['', 'getenv'],
	]),
];
```

### Expected Behavior
I would expect the parameters to be resolved the same way as they are if they are used as arguments in service definitions.

**Comment by xificurk** [comment]
Thank you :heart:

**Comment by dg** [comment]
I decided to remove this feature.

Resolving parameters takes time and performance, services can be created, and so on, but nobody uses parameters. Instead, I'll remove unresolved statements code will be cleaner.

**Comment by dakujem** [comment]
A problem I had with Nette 2.x was that once you _do_ actually want to quickly pull a parameter out of configuration, say for prototyping, it is not possible, because instead of a value, one gets a `Statement` object.
If it was possible to fetch the underlying value or "resolve" all or a subset of parameters, it would be awesome.
Something like the `Resolver::completeArguments`, that we could call on the container.

The usecase would be this:
```
$raw = $presenter->context->getParameters()['foo'];
$value = Something::resolve($raw);

// or
$value = $presenter->context->resolveParameter('foo');

// or
$presenter->context->resolveParameters();
$value = $presenter->context->getParameters()['foo'];
```
... I bet you get the idea, David @dg 

I am aware that the use case is not a good practice, yet this _does happen_ and is especially frustrating for people who have not mastered Nette, for example a React developer who just wants to quickly add this tiny parameter to the API for quick proof of concept...

**Comment by dakujem** [comment]
> Resolving parameters takes time and performance

👍

**Comment by dg** [comment]
What about this way?

```php
class Parameters
{
	private $params;

	function __construct(array $params)
	{
		$this->params = $params;
	}

	function get($key)
	{
		return $this->params[$key]
	}
}
```

Add it as service:


```
parameters:
	main:	
		a: ::getenv('xxx')
		b: xzy

service:
	- Parameters(%main%)
```

And than use `$params = $presenter->context->getByType(Parameters::class);` and `$params->get('a')` …

**Comment by dakujem** [comment]
I am injecting the parameters in groups, right.
A service like the oabove would "unpack" (evaluate) all the parameters, possibly not optimal for performance.

Anyway, this technique (injecting) is not something a newbie will come out with, trust me :-) I have been asked this over and over again ("How do I convert a Statement into a value?").
